### ISSUE TITLE
Add metadata to allow us to compare task performance in different types of scenes

### ISSUE THREAD

**Issue by Eugleo** [Eugleo/vlmrm#18]
We want to be able to compare performance in subsets of scenes, e.g. photorealistic vs CAD model, normal vs off-distribution, etc. Either we could hack this together by using e.g. video path in the visualization script and grouping the trajectories based on that, or we could add support for some general kind of metadata that would somehow be accessible in the visualization script.

**Comment by Dont-Care-Didnt-Ask** [comment]
Seems like one way to do this is to simply create several input files with respective subsets of the data.
E.g. `data/havitat/data_photorealistic.csv` and `data/havitat/data_cad.csv`.
Then we 
- put plots from different groups side by side
- or do grouped bar plots with an additional script.

First requires essentially zero effort; second can be done in an hour or two, and I would do it when we understand clearly, what kind of plots do we need, as visualization code is rarely generic enough.

As for general metadata, it looks to me that for each video (e.g. `bathroom_11.mp4` we could have metadata file `bathroom.json` with several fields like "type: realistic/cad, OOD: true/false" and so on). This approach is probably more general, although I don't think we strive for generality now.

**Comment by Eugleo** [comment]
Current solution: take a look at `_metadata_columns` in the notebook. The metadata are specified in the data.csv file together with the task labels, and are passed through the evaluator so that the notebook also sees them.
