### ISSUE TITLE
Suggest and implement a quantitative metric for model quality

### ISSUE THREAD

**Issue by Eugleo** [Eugleo/vlmrm#4]
Goal: simplify comparison of model performance.

**Comment by Dont-Care-Didnt-Ask** [comment]
I propose following setup.

Suppose you collected $N$ distinct trajectories. For each trajectory you have a textual description (e.g. "agent goes close to a door", or "agent topples something over").

**All-vs-all evaluation**
- compute similarities/rewards/smth between all trajectories and all descriptions, getting a matrix $S \in \mathbb{R}^{N \times N}$
- [optionally, normalize it somehow]
- for each row compute argmax, getting a matrix $\hat{S}$ with entries from ${0, 1}$ only (1 in place of maximum reward/similarity, 0 elsewhere)
- quantitative metric: compute $\frac{\text{diag}(\hat{S}).\text{sum}()}{N}$ (essentially similarity to identity matrix).
- visualization: heatmap. (It will probably not be too easy to read, but it should only show how far from identity matrix are we)

**Binary evaluations**
- Come up with some binary predicate, like "Does agent interact with any object during the video?"
- For **all** trajectories you have, assign a "yes"/"no" label -- now we essentially have a binary classification task
- Compute similarity/reward between all videos and description of positive outcome of the predicate (e.g. "Agent interacts with some object during the video")
- quantitative metric: any binary classification metric we want (Accuracy, Balanced Accuracy, Precision/Recall, ROC-AUC, Cohen Kappa)
 - visualization: I suppose, we can just report a table with various binary metrics here
 
 **Additional notes**
 - What if we have several trajectories for a single prompt, e.g. 3 demonstrations of agent going close to a door?
    - In all-vs-all, we average similarity across these (3) trajectories
    - In binary setup, we just treat them as additional samples
 - What if we have several prompt variations to describe each trajectory (e.g. "agent drops a cup" / "robot drops a cup") or to formulate a predicate (e.g. "agent interacts with some object" / "robot interacts with some object")?
    - In all-vs-all, we can 1) average similarity across these prompts or 2) compute metric twice, with different prompt. First approach reduces variance, second allows to test the stability of the results.
     - In binary setup, we can do the same.

**Comment by Eugleo** [comment]
Thanks, I agree with basically all of this. I guess in all-v-all we can use any matrix norm probably, or just cross entropy loss or something, since we only care about comparing the different models anyway.

**Comment by Eugleo** [comment]
Update: The description above is no longer up-to-date, we changed the framing a bit. Mike and I are already working on this.

**Comment by Eugleo** [comment]
I think there's more work we could do with visualization (e.g. #11 ) but I think we should just create new issues with ideas, and close this one.
